package org.dawnoftime.dotbv.client.gui.creative;

import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Blocks;
import org.dawnoftime.dotbv.registry.DoTBVBlocksRegistry;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

import static org.dawnoftime.dotbv.DoTBVCommon.MOD_ID;

public enum CreativeInventoryCategories {
    BUILDING("building", Blocks.STONE_BRICKS.asItem(),
            List.of(
                new SubTab("stones",
                        // Cobblestone
                        Blocks.COBBLESTONE.asItem(),
                        Blocks.COBBLESTONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COBBLESTONE_PLATE.get().asItem(),
                        Blocks.COBBLESTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COBBLESTONE_EDGE.get().asItem(),
                        Blocks.COBBLESTONE_WALL.asItem(),
                        // Mossy Cobblestone
                        Blocks.MOSSY_COBBLESTONE.asItem(),
                        Blocks.MOSSY_COBBLESTONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MOSSY_COBBLESTONE_PLATE.get().asItem(),
                        Blocks.MOSSY_COBBLESTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MOSSY_COBBLESTONE_EDGE.get().asItem(),
                        Blocks.MOSSY_COBBLESTONE_WALL.asItem(),
                        // Stone
                        Blocks.STONE.asItem(),
                        Blocks.STONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.STONE_PLATE.get().asItem(),
                        Blocks.STONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.STONE_EDGE.get().asItem(),
                        // Smooth Stone
                        Blocks.SMOOTH_STONE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_STONE_PLATE.get().asItem(),
                        Blocks.SMOOTH_STONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_STONE_EDGE.get().asItem(),
                        // Granite
                        Blocks.GRANITE.asItem(),
                        Blocks.GRANITE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRANITE_PLATE.get().asItem(),
                        Blocks.GRANITE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRANITE_EDGE.get().asItem(),
                        Blocks.GRANITE_WALL.asItem(),
                        // Polished Granite
                        Blocks.POLISHED_GRANITE.asItem(),
                        Blocks.POLISHED_GRANITE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_GRANITE_PLATE.get().asItem(),
                        Blocks.POLISHED_GRANITE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_GRANITE_EDGE.get().asItem(),
                        // Diorite
                        Blocks.DIORITE.asItem(),
                        Blocks.DIORITE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DIORITE_PLATE.get().asItem(),
                        Blocks.DIORITE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DIORITE_EDGE.get().asItem(),
                        Blocks.DIORITE_WALL.asItem(),
                        // Polished Diorite
                        Blocks.POLISHED_DIORITE.asItem(),
                        Blocks.POLISHED_DIORITE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_DIORITE_PLATE.get().asItem(),
                        Blocks.POLISHED_DIORITE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_DIORITE_EDGE.get().asItem(),
                        // Andesite
                        Blocks.ANDESITE.asItem(),
                        Blocks.ANDESITE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ANDESITE_PLATE.get().asItem(),
                        Blocks.ANDESITE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ANDESITE_EDGE.get().asItem(),
                        Blocks.ANDESITE_WALL.asItem(),
                        // Polished Andesite
                        Blocks.POLISHED_ANDESITE.asItem(),
                        Blocks.POLISHED_ANDESITE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_ANDESITE_PLATE.get().asItem(),
                        Blocks.POLISHED_ANDESITE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_ANDESITE_EDGE.get().asItem(),
                        // Deepslate
                        Blocks.DEEPSLATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DEEPSLATE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DEEPSLATE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DEEPSLATE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DEEPSLATE_EDGE.get().asItem(),
                        // Cobbled Deepslate
                        Blocks.COBBLED_DEEPSLATE.asItem(),
                        Blocks.COBBLED_DEEPSLATE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COBBLED_DEEPSLATE_PLATE.get().asItem(),
                        Blocks.COBBLED_DEEPSLATE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COBBLED_DEEPSLATE_EDGE.get().asItem(),
                        Blocks.COBBLED_DEEPSLATE_WALL.asItem(),
                        // Polished Deepslate
                        Blocks.POLISHED_DEEPSLATE.asItem(),
                        Blocks.POLISHED_DEEPSLATE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_DEEPSLATE_PLATE.get().asItem(),
                        Blocks.POLISHED_DEEPSLATE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_DEEPSLATE_EDGE.get().asItem(),
                        Blocks.POLISHED_DEEPSLATE_WALL.asItem(),
                        // Calcite
                        Blocks.CALCITE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CALCITE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CALCITE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CALCITE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CALCITE_EDGE.get().asItem(),
                        // Tuff
                        Blocks.TUFF.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TUFF_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TUFF_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TUFF_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TUFF_EDGE.get().asItem(),
                        // Dripstone Block
                        Blocks.DRIPSTONE_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DRIPSTONE_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DRIPSTONE_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DRIPSTONE_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DRIPSTONE_BLOCK_EDGE.get().asItem(),
                        // Packed Mud
                        Blocks.PACKED_MUD.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PACKED_MUD_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PACKED_MUD_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PACKED_MUD_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PACKED_MUD_EDGE.get().asItem()
                ),
                new SubTab("bricks",
                        // Stone Bricks
                        Blocks.STONE_BRICKS.asItem(),
                        Blocks.STONE_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.STONE_BRICKS_PLATE.get().asItem(),
                        Blocks.STONE_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.STONE_BRICKS_EDGE.get().asItem(),
                        Blocks.STONE_BRICK_WALL.asItem(),
                        // Mossy Stone Bricks
                        Blocks.MOSSY_STONE_BRICKS.asItem(),
                        Blocks.MOSSY_STONE_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MOSSY_STONE_BRICKS_PLATE.get().asItem(),
                        Blocks.MOSSY_STONE_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MOSSY_STONE_BRICKS_EDGE.get().asItem(),
                        Blocks.MOSSY_STONE_BRICK_WALL.asItem(),
                        // Cracked Stone Bricks
                        Blocks.CRACKED_STONE_BRICKS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_STONE_BRICKS_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_STONE_BRICKS_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_STONE_BRICKS_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_STONE_BRICKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_STONE_BRICKS_WALL.get().asItem(),
                        // Deepslate Bricks
                        Blocks.DEEPSLATE_BRICKS.asItem(),
                        Blocks.DEEPSLATE_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DEEPSLATE_BRICKS_PLATE.get().asItem(),
                        Blocks.DEEPSLATE_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DEEPSLATE_BRICKS_EDGE.get().asItem(),
                        Blocks.DEEPSLATE_BRICK_WALL.asItem(),
                        // Cracked Deepslate Bricks
                        Blocks.CRACKED_DEEPSLATE_BRICKS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_DEEPSLATE_BRICKS_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_DEEPSLATE_BRICKS_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_DEEPSLATE_BRICKS_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_DEEPSLATE_BRICKS_EDGE.get().asItem(),
                        // Deepslate Tiles
                        Blocks.DEEPSLATE_TILES.asItem(),
                        Blocks.DEEPSLATE_TILE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DEEPSLATE_TILES_PLATE.get().asItem(),
                        Blocks.DEEPSLATE_TILE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DEEPSLATE_TILES_EDGE.get().asItem(),
                        Blocks.DEEPSLATE_TILE_WALL.asItem(),
                        // Cracked Deepslate Tiles
                        Blocks.CRACKED_DEEPSLATE_TILES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_DEEPSLATE_TILES_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_DEEPSLATE_TILES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_DEEPSLATE_TILES_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_DEEPSLATE_TILES_EDGE.get().asItem(),
                        // Bricks
                        Blocks.BRICKS.asItem(),
                        Blocks.BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BRICKS_PLATE.get().asItem(),
                        Blocks.BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BRICKS_EDGE.get().asItem(),
                        Blocks.BRICK_WALL.asItem(),
                        // Mud Bricks
                        Blocks.MUD_BRICKS.asItem(),
                        Blocks.MUD_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MUD_BRICKS_PLATE.get().asItem(),
                        Blocks.MUD_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MUD_BRICKS_EDGE.get().asItem(),
                        Blocks.MUD_BRICK_WALL.asItem()
                ),
                new SubTab("others",
                        Blocks.SANDSTONE.asItem(),
                        Blocks.SANDSTONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SANDSTONE_PLATE.get().asItem(),
                        Blocks.SANDSTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SANDSTONE_EDGE.get().asItem(),
                        Blocks.SANDSTONE_WALL.asItem(),
                        Blocks.SMOOTH_SANDSTONE.asItem(),
                        Blocks.SMOOTH_SANDSTONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_SANDSTONE_PLATE.get().asItem(),
                        Blocks.SMOOTH_SANDSTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_SANDSTONE_EDGE.get().asItem(),
                        Blocks.CUT_SANDSTONE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CUT_SANDSTONE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CUT_SANDSTONE_PLATE.get().asItem(),
                        Blocks.CUT_SANDSTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CUT_SANDSTONE_EDGE.get().asItem(),
                        Blocks.CHISELED_SANDSTONE.asItem(),
                        // Red Sandstone
                        Blocks.RED_SANDSTONE.asItem(),
                        Blocks.RED_SANDSTONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_SANDSTONE_PLATE.get().asItem(),
                        Blocks.RED_SANDSTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_SANDSTONE_EDGE.get().asItem(),
                        Blocks.RED_SANDSTONE_WALL.asItem(),
                        // Smooth Red Sandstone
                        Blocks.SMOOTH_RED_SANDSTONE.asItem(),
                        Blocks.SMOOTH_RED_SANDSTONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_RED_SANDSTONE_PLATE.get().asItem(),
                        Blocks.SMOOTH_RED_SANDSTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_RED_SANDSTONE_EDGE.get().asItem(),
                        // Cut Red Sandstone
                        Blocks.CUT_RED_SANDSTONE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CUT_RED_SANDSTONE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CUT_RED_SANDSTONE_PLATE.get().asItem(),
                        Blocks.CUT_RED_SANDSTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CUT_RED_SANDSTONE_EDGE.get().asItem(),
                        // Prismarine
                        Blocks.PRISMARINE.asItem(),
                        Blocks.PRISMARINE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PRISMARINE_PLATE.get().asItem(),
                        Blocks.PRISMARINE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PRISMARINE_EDGE.get().asItem(),
                        Blocks.PRISMARINE_WALL.asItem(),
                        // Prismarine Bricks
                        Blocks.PRISMARINE_BRICKS.asItem(),
                        Blocks.PRISMARINE_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PRISMARINE_BRICKS_PLATE.get().asItem(),
                        Blocks.PRISMARINE_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PRISMARINE_BRICKS_EDGE.get().asItem(),
                        // Dark Prismarine
                        Blocks.DARK_PRISMARINE.asItem(),
                        Blocks.DARK_PRISMARINE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_PRISMARINE_PLATE.get().asItem(),
                        Blocks.DARK_PRISMARINE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_PRISMARINE_EDGE.get().asItem()
                ),
                new SubTab("materials",
                        // Coal
                        Blocks.COAL_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COAL_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COAL_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COAL_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COAL_BLOCK_EDGE.get().asItem(),
                        // Iron
                        Blocks.IRON_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.IRON_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.IRON_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.IRON_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.IRON_BLOCK_EDGE.get().asItem(),
                        // Gold
                        Blocks.GOLD_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GOLD_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GOLD_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GOLD_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GOLD_BLOCK_EDGE.get().asItem(),
                        // Lapis
                        Blocks.LAPIS_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LAPIS_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LAPIS_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LAPIS_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LAPIS_BLOCK_EDGE.get().asItem(),
                        // Diamond
                        Blocks.DIAMOND_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DIAMOND_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DIAMOND_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DIAMOND_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DIAMOND_BLOCK_EDGE.get().asItem(),
                        // Netherite
                        Blocks.NETHERITE_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHERITE_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHERITE_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHERITE_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHERITE_BLOCK_EDGE.get().asItem(),
                        // Amethyst
                        Blocks.AMETHYST_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.AMETHYST_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.AMETHYST_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.AMETHYST_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.AMETHYST_BLOCK_EDGE.get().asItem(),
                        // Waxed Copper Block
                        Blocks.WAXED_COPPER_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_COPPER_BLOCK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_COPPER_BLOCK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_COPPER_BLOCK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_COPPER_BLOCK_EDGE.get().asItem(),
                        // Waxed Cut Copper
                        Blocks.WAXED_CUT_COPPER.asItem(),
                        Blocks.WAXED_CUT_COPPER_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_CUT_COPPER_PLATE.get().asItem(),
                        Blocks.WAXED_CUT_COPPER_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_CUT_COPPER_EDGE.get().asItem(),
                        // Waxed Exposed Copper
                        Blocks.WAXED_EXPOSED_COPPER.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_EXPOSED_COPPER_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_EXPOSED_COPPER_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_EXPOSED_COPPER_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_EXPOSED_COPPER_EDGE.get().asItem(),
                        // Waxed Exposed Cut Copper
                        Blocks.WAXED_EXPOSED_CUT_COPPER.asItem(),
                        Blocks.WAXED_EXPOSED_CUT_COPPER_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_EXPOSED_CUT_COPPER_PLATE.get().asItem(),
                        Blocks.WAXED_EXPOSED_CUT_COPPER_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_EXPOSED_CUT_COPPER_EDGE.get().asItem(),
                        // Waxed Weathered Copper
                        Blocks.WAXED_WEATHERED_COPPER.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_WEATHERED_COPPER_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_WEATHERED_COPPER_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_WEATHERED_COPPER_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_WEATHERED_COPPER_EDGE.get().asItem(),
                        // Waxed Weathered Cut Copper
                        Blocks.WAXED_WEATHERED_CUT_COPPER.asItem(),
                        Blocks.WAXED_WEATHERED_CUT_COPPER_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_WEATHERED_CUT_COPPER_PLATE.get().asItem(),
                        Blocks.WAXED_WEATHERED_CUT_COPPER_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_WEATHERED_CUT_COPPER_EDGE.get().asItem(),
                        // Waxed Oxidized Copper
                        Blocks.WAXED_OXIDIZED_COPPER.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_OXIDIZED_COPPER_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_OXIDIZED_COPPER_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_OXIDIZED_COPPER_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_OXIDIZED_COPPER_EDGE.get().asItem(),
                        // Waxed Oxidized Cut Copper
                        Blocks.WAXED_OXIDIZED_CUT_COPPER.asItem(),
                        Blocks.WAXED_OXIDIZED_CUT_COPPER_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_OXIDIZED_CUT_COPPER_PLATE.get().asItem(),
                        Blocks.WAXED_OXIDIZED_CUT_COPPER_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WAXED_OXIDIZED_CUT_COPPER_EDGE.get().asItem()
                )
            )
    ),

    NATURALS("naturals", Blocks.OAK_LOG.asItem(),
            List.of(
                new SubTab("wood",
                        // Oak
                        Blocks.OAK_PLANKS.asItem(),
                        Blocks.OAK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_PLANKS_PLATE.get().asItem(),
                        Blocks.OAK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_OAK_LOG.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_PERGOLA.get().asItem(),
                        Blocks.OAK_FENCE.asItem(),
                        Blocks.OAK_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_LATTICE.get().asItem(),
                        Blocks.OAK_DOOR.asItem(),
                        Blocks.OAK_TRAPDOOR.asItem(),
                        Blocks.OAK_LEAVES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_LEAVES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.OAK_LEAVES_EDGE.get().asItem(),
                        // Spruce
                        Blocks.SPRUCE_PLANKS.asItem(),
                        Blocks.SPRUCE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_PLANKS_PLATE.get().asItem(),
                        Blocks.SPRUCE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_SPRUCE_LOG.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_PERGOLA.get().asItem(),
                        Blocks.SPRUCE_FENCE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_LATTICE.get().asItem(),
                        Blocks.SPRUCE_FENCE_GATE.asItem(),
                        Blocks.SPRUCE_DOOR.asItem(),
                        Blocks.SPRUCE_TRAPDOOR.asItem(),
                        Blocks.SPRUCE_LEAVES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_LEAVES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SPRUCE_LEAVES_EDGE.get().asItem(),
                        // Birch
                        Blocks.BIRCH_PLANKS.asItem(),
                        Blocks.BIRCH_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_PLANKS_PLATE.get().asItem(),
                        Blocks.BIRCH_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_BIRCH_LOG.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_PERGOLA.get().asItem(),
                        Blocks.BIRCH_FENCE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_LATTICE.get().asItem(),
                        Blocks.BIRCH_DOOR.asItem(),
                        Blocks.BIRCH_TRAPDOOR.asItem(),
                        Blocks.BIRCH_LEAVES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_LEAVES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BIRCH_LEAVES_EDGE.get().asItem(),
                        // Jungle
                        Blocks.JUNGLE_PLANKS.asItem(),
                        Blocks.JUNGLE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_PLANKS_PLATE.get().asItem(),
                        Blocks.JUNGLE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_JUNGLE_LOG.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_PERGOLA.get().asItem(),
                        Blocks.JUNGLE_FENCE.asItem(),
                        Blocks.JUNGLE_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_LATTICE.get().asItem(),
                        Blocks.JUNGLE_DOOR.asItem(),
                        Blocks.JUNGLE_TRAPDOOR.asItem(),
                        Blocks.JUNGLE_LEAVES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_LEAVES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.JUNGLE_LEAVES_EDGE.get().asItem(),
                        // Acacia
                        Blocks.ACACIA_PLANKS.asItem(),
                        Blocks.ACACIA_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_PLANKS_PLATE.get().asItem(),
                        Blocks.ACACIA_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_ACACIA_LOG.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_PERGOLA.get().asItem(),
                        Blocks.ACACIA_FENCE.asItem(),
                        Blocks.ACACIA_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_LATTICE.get().asItem(),
                        Blocks.ACACIA_DOOR.asItem(),
                        Blocks.ACACIA_TRAPDOOR.asItem(),
                        Blocks.ACACIA_LEAVES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_LEAVES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ACACIA_LEAVES_EDGE.get().asItem(),
                        // Dark Oak
                        Blocks.DARK_OAK_PLANKS.asItem(),
                        Blocks.DARK_OAK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_PLANKS_PLATE.get().asItem(),
                        Blocks.DARK_OAK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_DARK_OAK_LOG.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_PERGOLA.get().asItem(),
                        Blocks.DARK_OAK_FENCE.asItem(),
                        Blocks.DARK_OAK_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_LATTICE.get().asItem(),
                        Blocks.DARK_OAK_DOOR.asItem(),
                        Blocks.DARK_OAK_TRAPDOOR.asItem(),
                        Blocks.DARK_OAK_LEAVES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_LEAVES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DARK_OAK_LEAVES_EDGE.get().asItem(),
                        // Cherry
                        Blocks.CHERRY_PLANKS.asItem(),
                        Blocks.CHERRY_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_PLANKS_PLATE.get().asItem(),
                        Blocks.CHERRY_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_CHERRY_LOG.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_PERGOLA.get().asItem(),
                        Blocks.CHERRY_FENCE.asItem(),
                        Blocks.CHERRY_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_LATTICE.get().asItem(),
                        Blocks.CHERRY_DOOR.asItem(),
                        Blocks.CHERRY_TRAPDOOR.asItem(),
                        Blocks.CHERRY_LEAVES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_LEAVES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CHERRY_LEAVES_EDGE.get().asItem(),
                        // Mangrove
                        Blocks.MANGROVE_PLANKS.asItem(),
                        Blocks.MANGROVE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_PLANKS_PLATE.get().asItem(),
                        Blocks.MANGROVE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_MANGROVE_LOG.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_PERGOLA.get().asItem(),
                        Blocks.MANGROVE_FENCE.asItem(),
                        Blocks.MANGROVE_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_LATTICE.get().asItem(),
                        Blocks.MANGROVE_DOOR.asItem(),
                        Blocks.MANGROVE_TRAPDOOR.asItem(),
                        Blocks.MANGROVE_LEAVES.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_LEAVES_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MANGROVE_LEAVES_EDGE.get().asItem(),
                        // Bamboo
                        Blocks.BAMBOO_PLANKS.asItem(),
                        Blocks.BAMBOO_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BAMBOO_PLANKS_PLATE.get().asItem(),
                        Blocks.BAMBOO_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BAMBOO_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BAMBOO_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BAMBOO_SUPPORT_BEAM.get().asItem(),
                        Blocks.BAMBOO_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BAMBOO_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BAMBOO_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BAMBOO_PERGOLA.get().asItem(),
                        Blocks.BAMBOO_FENCE.asItem(),
                        Blocks.BAMBOO_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BAMBOO_LATTICE.get().asItem(),
                        Blocks.BAMBOO_DOOR.asItem(),
                        Blocks.BAMBOO_TRAPDOOR.asItem()
                ),
                new SubTab("path",
                        Blocks.GRAVEL.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAVEL_SLAB.get().asItem(),
                        Blocks.SAND.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SAND_SLAB.get().asItem(),
                        Blocks.GRASS_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRASS_BLOCK_SLAB.get().asItem(),
                        Blocks.PODZOL.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PODZOL_SLAB.get().asItem(),
                        Blocks.MYCELIUM.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MYCELIUM_SLAB.get().asItem(),
                        Blocks.DIRT_PATH.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DIRT_PATH_SLAB.get().asItem(),
                        Blocks.DIRT.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.DIRT_SLAB.get().asItem(),
                        Blocks.COARSE_DIRT.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.COARSE_DIRT_SLAB.get().asItem(),
                        Blocks.ROOTED_DIRT.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ROOTED_DIRT_SLAB.get().asItem(),
                        Blocks.MUD.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MUD_SLAB.get().asItem(),
                        Blocks.CLAY.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CLAY_SLAB.get().asItem(),
                        Blocks.RED_SAND.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_SAND_SLAB.get().asItem(),
                        Blocks.MOSS_BLOCK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MOSS_BLOCK_SLAB.get().asItem(),
                        // Ice
                        Blocks.ICE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ICE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ICE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ICE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ICE_EDGE.get().asItem(),
                        // Packed Ice
                        Blocks.PACKED_ICE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PACKED_ICE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PACKED_ICE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PACKED_ICE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PACKED_ICE_EDGE.get().asItem(),
                        // Blue Ice
                        Blocks.BLUE_ICE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_ICE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_ICE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_ICE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_ICE_EDGE.get().asItem()
                )
            )
    ),

    COLORED("colored", Blocks.TERRACOTTA.asItem(),
            List.of(
                new SubTab("terracotta",
                        // Neutrals: light → dark
                        Blocks.TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.TERRACOTTA_WALL.get().asItem(),
                        Blocks.WHITE_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_TERRACOTTA_WALL.get().asItem(),
                        Blocks.LIGHT_GRAY_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_TERRACOTTA_WALL.get().asItem(),
                        Blocks.GRAY_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_TERRACOTTA_WALL.get().asItem(),
                        Blocks.BLACK_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_TERRACOTTA_WALL.get().asItem(),
                        // Chromatic: red → orange → yellow → lime → green → cyan → light blue → blue → purple → magenta → pink → brown
                        Blocks.RED_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_TERRACOTTA_WALL.get().asItem(),
                        Blocks.ORANGE_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_TERRACOTTA_WALL.get().asItem(),
                        Blocks.YELLOW_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_TERRACOTTA_WALL.get().asItem(),
                        Blocks.LIME_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_TERRACOTTA_WALL.get().asItem(),
                        Blocks.GREEN_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_TERRACOTTA_WALL.get().asItem(),
                        Blocks.CYAN_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_TERRACOTTA_WALL.get().asItem(),
                        Blocks.LIGHT_BLUE_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_TERRACOTTA_WALL.get().asItem(),
                        Blocks.BLUE_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_TERRACOTTA_WALL.get().asItem(),
                        Blocks.PURPLE_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_TERRACOTTA_WALL.get().asItem(),
                        Blocks.MAGENTA_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_TERRACOTTA_WALL.get().asItem(),
                        Blocks.PINK_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_TERRACOTTA_WALL.get().asItem(),
                        Blocks.BROWN_TERRACOTTA.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_TERRACOTTA_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_TERRACOTTA_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_TERRACOTTA_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_TERRACOTTA_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_TERRACOTTA_WALL.get().asItem()
                ),
                new SubTab("concrete",
                        // Neutrals: light → dark
                        Blocks.WHITE_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WHITE_CONCRETE_WALL.get().asItem(),
                        Blocks.LIGHT_GRAY_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_GRAY_CONCRETE_WALL.get().asItem(),
                        Blocks.GRAY_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GRAY_CONCRETE_WALL.get().asItem(),
                        Blocks.BLACK_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACK_CONCRETE_WALL.get().asItem(),
                        // Chromatic: red → orange → yellow → lime → green → cyan → light blue → blue → purple → magenta → pink → brown
                        Blocks.RED_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_CONCRETE_WALL.get().asItem(),
                        Blocks.ORANGE_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.ORANGE_CONCRETE_WALL.get().asItem(),
                        Blocks.YELLOW_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.YELLOW_CONCRETE_WALL.get().asItem(),
                        Blocks.LIME_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIME_CONCRETE_WALL.get().asItem(),
                        Blocks.GREEN_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.GREEN_CONCRETE_WALL.get().asItem(),
                        Blocks.CYAN_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CYAN_CONCRETE_WALL.get().asItem(),
                        Blocks.LIGHT_BLUE_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.LIGHT_BLUE_CONCRETE_WALL.get().asItem(),
                        Blocks.BLUE_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLUE_CONCRETE_WALL.get().asItem(),
                        Blocks.PURPLE_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPLE_CONCRETE_WALL.get().asItem(),
                        Blocks.MAGENTA_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.MAGENTA_CONCRETE_WALL.get().asItem(),
                        Blocks.PINK_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PINK_CONCRETE_WALL.get().asItem(),
                        Blocks.BROWN_CONCRETE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_CONCRETE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_CONCRETE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_CONCRETE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_CONCRETE_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BROWN_CONCRETE_WALL.get().asItem()
                )
            )
    ),

    DIMENSIONS("dimensions", Blocks.RED_NETHER_BRICKS.asItem(),
            List.of(
                new SubTab("dimensions",
                        // Quartz Block
                        Blocks.QUARTZ_BLOCK.asItem(),
                        Blocks.QUARTZ_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.QUARTZ_BLOCK_PLATE.get().asItem(),
                        Blocks.QUARTZ_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.QUARTZ_BLOCK_EDGE.get().asItem(),
                        // Quartz Pillar
                        Blocks.QUARTZ_PILLAR.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.QUARTZ_PILLAR_PLATE.get().asItem(),
                        // Quartz Bricks
                        Blocks.QUARTZ_BRICKS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.QUARTZ_BRICKS_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.QUARTZ_BRICKS_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.QUARTZ_BRICKS_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.QUARTZ_BRICKS_EDGE.get().asItem(),
                        // Smooth Quartz
                        Blocks.SMOOTH_QUARTZ.asItem(),
                        Blocks.SMOOTH_QUARTZ_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_QUARTZ_PLATE.get().asItem(),
                        Blocks.SMOOTH_QUARTZ_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_QUARTZ_EDGE.get().asItem(),
                        // Netherrack
                        Blocks.NETHERRACK.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHERRACK_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHERRACK_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHERRACK_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHERRACK_EDGE.get().asItem(),
                        // Nether Bricks
                        Blocks.NETHER_BRICKS.asItem(),
                        Blocks.NETHER_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHER_BRICKS_PLATE.get().asItem(),
                        Blocks.NETHER_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.NETHER_BRICKS_EDGE.get().asItem(),
                        Blocks.NETHER_BRICK_WALL.asItem(),
                        Blocks.NETHER_BRICK_FENCE.asItem(),
                        // Cracked Nether Bricks
                        Blocks.CRACKED_NETHER_BRICKS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_NETHER_BRICKS_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_NETHER_BRICKS_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_NETHER_BRICKS_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRACKED_NETHER_BRICKS_EDGE.get().asItem(),
                        // Red Nether Bricks
                        Blocks.RED_NETHER_BRICKS.asItem(),
                        Blocks.RED_NETHER_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_NETHER_BRICKS_PLATE.get().asItem(),
                        Blocks.RED_NETHER_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.RED_NETHER_BRICKS_EDGE.get().asItem(),
                        Blocks.RED_NETHER_BRICK_WALL.asItem(),
                        // Smooth Basalt
                        Blocks.SMOOTH_BASALT.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_BASALT_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_BASALT_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_BASALT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SMOOTH_BASALT_EDGE.get().asItem(),
                        // Blackstone
                        Blocks.BLACKSTONE.asItem(),
                        Blocks.BLACKSTONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACKSTONE_PLATE.get().asItem(),
                        Blocks.BLACKSTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.BLACKSTONE_EDGE.get().asItem(),
                        Blocks.BLACKSTONE_WALL.asItem(),
                        // Polished Blackstone
                        Blocks.POLISHED_BLACKSTONE.asItem(),
                        Blocks.POLISHED_BLACKSTONE_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_BLACKSTONE_PLATE.get().asItem(),
                        Blocks.POLISHED_BLACKSTONE_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_BLACKSTONE_EDGE.get().asItem(),
                        Blocks.POLISHED_BLACKSTONE_WALL.asItem(),
                        // Polished Blackstone Bricks
                        Blocks.POLISHED_BLACKSTONE_BRICKS.asItem(),
                        Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_BLACKSTONE_BRICKS_PLATE.get().asItem(),
                        Blocks.POLISHED_BLACKSTONE_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.POLISHED_BLACKSTONE_BRICKS_EDGE.get().asItem(),
                        Blocks.POLISHED_BLACKSTONE_BRICK_WALL.asItem(),
                        // End Stone
                        Blocks.END_STONE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.END_STONE_STAIRS.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.END_STONE_PLATE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.END_STONE_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.END_STONE_EDGE.get().asItem(),
                        // End Stone Bricks
                        Blocks.END_STONE_BRICKS.asItem(),
                        Blocks.END_STONE_BRICK_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.END_STONE_BRICKS_PLATE.get().asItem(),
                        Blocks.END_STONE_BRICK_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.END_STONE_BRICKS_EDGE.get().asItem(),
                        Blocks.END_STONE_BRICK_WALL.asItem(),
                        // Purpur Block
                        Blocks.PURPUR_BLOCK.asItem(),
                        Blocks.PURPUR_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPUR_BLOCK_PLATE.get().asItem(),
                        Blocks.PURPUR_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.PURPUR_BLOCK_EDGE.get().asItem()
                ),
                new SubTab("wood_dimensions",
                        // Nylium / Soul
                        Blocks.CRIMSON_NYLIUM.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_NYLIUM_SLAB.get().asItem(),
                        Blocks.WARPED_NYLIUM.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_NYLIUM_SLAB.get().asItem(),
                        Blocks.SOUL_SAND.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SOUL_SAND_SLAB.get().asItem(),
                        Blocks.SOUL_SOIL.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.SOUL_SOIL_SLAB.get().asItem(),
                        // Crimson
                        Blocks.CRIMSON_PLANKS.asItem(),
                        Blocks.CRIMSON_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_PLANKS_PLATE.get().asItem(),
                        Blocks.CRIMSON_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_CRIMSON_STEM.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_PERGOLA.get().asItem(),
                        Blocks.CRIMSON_FENCE.asItem(),
                        Blocks.CRIMSON_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.CRIMSON_LATTICE.get().asItem(),
                        Blocks.CRIMSON_DOOR.asItem(),
                        Blocks.CRIMSON_TRAPDOOR.asItem(),
                        Blocks.NETHER_WART_BLOCK.asItem(),
                        // Warped
                        Blocks.WARPED_PLANKS.asItem(),
                        Blocks.WARPED_STAIRS.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_PLANKS_PLATE.get().asItem(),
                        Blocks.WARPED_SLAB.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_PLANKS_EDGE.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_SUPPORT_SLAB.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_SUPPORT_BEAM.get().asItem(),
                        Blocks.STRIPPED_WARPED_STEM.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_BEAM.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_WALL.get().asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_PERGOLA.get().asItem(),
                        Blocks.WARPED_FENCE.asItem(),
                        Blocks.WARPED_FENCE_GATE.asItem(),
                        DoTBVBlocksRegistry.INSTANCE.WARPED_LATTICE.get().asItem(),
                        Blocks.WARPED_DOOR.asItem(),
                        Blocks.WARPED_TRAPDOOR.asItem(),
                        Blocks.WARPED_WART_BLOCK.asItem()
                )
            )
    );


    private final String name;
    private final Component translation;
    private final Item iconItem;
    private final ArrayList<Item> items = new ArrayList<>();
    private final List<SubTab> subTabs;

    // Constructor for categories with direct item lists (no subtabs)
    CreativeInventoryCategories(String name, Item iconItem, Item... items) {
        this.name = name;
        this.translation = Component.translatable("gui." + MOD_ID + "." + name);
        this.iconItem = iconItem;
        this.subTabs = List.of();
        Collections.addAll(this.items, items);
    }

    // Constructor for categories with subtabs
    CreativeInventoryCategories(String name, Item iconItem, List<SubTab> subTabs) {
        this.name = name;
        this.translation = Component.translatable("gui." + MOD_ID + "." + name);
        this.iconItem = iconItem;
        this.subTabs = subTabs;
    }

    public String getName() {
        return this.name;
    }

    public Item getIconItem() {
        return this.iconItem;
    }

    public Component getTranslation() {
        return this.translation;
    }

    public List<Item> getItems() {
        if (!subTabs.isEmpty()) {
            return subTabs.stream()
                    .flatMap(sub -> sub.items().stream())
                    .collect(Collectors.toList());
        }
        return this.items;
    }

    public List<SubTab> getSubTabs() {
        return this.subTabs;
    }

    public boolean hasSubTabs() {
        return !this.subTabs.isEmpty();
    }

    public List<Item> getSubTabItems(int subTabIndex) {
        if (!hasSubTabs()) return this.items;
        int idx = Math.max(0, Math.min(subTabIndex, subTabs.size() - 1));
        return subTabs.get(idx).items();
    }

    public record SubTab(String nameKey, ResourceLocation textureOn, ResourceLocation textureOff, List<Item> items) {
        public SubTab(String nameKey, Item... items) {
            this(nameKey,
                new ResourceLocation(MOD_ID, "textures/gui/subtab_" + nameKey + "_on.png"),
                new ResourceLocation(MOD_ID, "textures/gui/subtab_" + nameKey + "_off.png"),
                Arrays.asList(items));
        }

        public Component getTooltip() {
            return Component.translatable("tooltip." + MOD_ID + ".subtab." + nameKey);
        }
    }
}
